### YamlMime:FAQ
metadata:
  title: Часто задаваемые вопросы по безопасности
  description: оставайтесь в курсе самых популярных вопросов и ответов на HoloLens устройств смешанной реальности.
  ms.assetid: bd55ecd1-697a-4b09-8274-48d1499fcb0b
  author: pawinfie
  ms.author: pawinfie
  ms.date: 02/19/2020
  keywords: hololens, Windows Mixed Reality, security
  ms.prod: hololens
  ms.sitesec: library
  ms.topic: article
  audience: ITPro
  ms.localizationpriority: medium
  ms.custom:
  - CI 111456
  - CSSTroubleshooting
  manager: bradke
  ms.openlocfilehash: 108f2e4c0aa9af251ecb6bc5185c7803ae51b5f7
  ms.sourcegitcommit: c43cd2f450b643ad4fc8e749235d03ec5aa3ffcf
  ms.translationtype: MT
  ms.contentlocale: ru-RU
  ms.lasthandoff: 07/12/2021
  ms.locfileid: "113637283"
title: Часто задаваемые вопросы о безопасности HoloLens (1-го поколения)
summary: ''
sections:
- name: Не учитывается
  questions:
  - question: >
      какой уровень защиты данных предлагает HoloLens 1?
    answer: >
      * см. [HoloLensное (первое поколение) шифрование BitLocker](hololens1-encryption.md)
  - question: >
      Какой тип беспроводной сети используется?
    answer: >
      * 802.11 ac и Bluetooth 4,1 LE
  - question: >
      Какой тип архитектуры включен?  Например: наведите указатель мыши на точку, сеть или что-нибудь другое?
    answer: >
      * Wi-Fi можно использовать в режиме инфраструктуры для связи с другими точками беспроводного доступа.

      * Bluetooth можно использовать для обмена данными между одноранговой стороной между несколькими HoloLens, если приложение клиента поддерживает его или другие устройства Bluetooth.
  - question: >
      Что такое Идентификатор FCC?
    answer: >
      * C3K1688
  - question: >
      Какой диапазон частоты и каналы работают на устройстве и можно ли его настроить?
    answer: >
      * Wi-Fi. Диапазон частот не настраивается пользователем и зависит от страны использования. В Wi-Fi США используются каналы 2,4 ГГц (1-11) и 5 ГГц (36-64, 100-165).

      * Bluetooth: Bluetooth использует стандартный диапазон с частотой 2,4 2.48 ггц.
  - question: >
      Может ли устройство разрешать или блокировать определенные частоты?
    answer: >
      * Это не может быть управляемым пользователем или устройством.
  - question: >
      Каков уровень мощности для передачи и получения? Он является изменяемым? Что такое диапазон операций?
    answer: >
      * Наши стандарты тестирования выбросов можно найти [здесь](https://fccid.io/C3K1688). Диапазон операций сильно зависит от точки доступа и среды, но она примерно эквивалентна другим высококачественным телефонам, планшетам и компьютерам.
  - question: >
      Что такое Рабочая нагрузка/жизненный цикл для нормальной работы?
    answer: >
      * 2-3 часов активного использования и до двух недель времени в режиме ожидания

      * Время существования аккумулятора недоступно.
  - question: >
      Что такое передача и получение поведения, если средство не находится в диапазоне?
    answer: >
      * HoloLens передачи и получения соответствует стандартному шаблону Wi-Fi/Bluetooth. На границе диапазона вы, вероятно, заметите, что входные данные будут прерывистыми до тех пор, пока он не будет полностью отключен, но после возврата в диапазон он должен быстро подключиться.
  - question: >
      Что такое плотность развертывания на квадратный фут?
    answer: >
      * Это зависит от сетевой инфраструктуры.
  - question: >
      Может ли устройство использовать инфраструктуру в качестве клиента?
    answer: >
      * Да
  - question: >
      Какой протокол используется?
    answer: >
      * HoloLens не использует собственные протоколы
  - question: >
      Частота обновления ОС — Какова частота обновлений ОС для HL?  Задано ли расписание?  Выпускают исправления системы безопасности Майкрософт по мере необходимости и т. д.
    answer: >
      * корпорация майкрософт предоставляет обновления ос для HoloLens точно так же, как и для Windows 10. Обычно существует два основных обновления в год: один в пружине, один в пожертве. так как HoloLens является Windows устройством, концепция обновления аналогична той, что и для любого другого Windows устройства. корпорация майкрософт выпускает исправления безопасности по мере необходимости и соответствует той же концепции, что и на любом другом устройстве Windows.
  - question: >
      Усиление защиты ОС — какие варианты загружают операционную систему?  Можно ли удалять или завершать ненужные приложения или службы?
    answer: >
      * HoloLens ведет себя как смартфон. она сравнима с другими современными Windows устройствами. HoloLens можно управлять с помощью Microsoft Intune или других современных решений по управлению устройствами, таких как MobileIron, Airwatch или соти. В этих системах управления можно задать политики для размещения политик безопасности на устройстве и для защиты устройства. При необходимости также можно удалить все ненужные приложения.
  - question: >
      Как будут управляться и обновляться программные приложения? Какой элемент управления должен определять, какие приложения загружаются, а также процесс обновления приложений для приложений, которые находятся в магазине Майкрософт?
    answer: >
      * HoloLens получает программные приложения только через хранилище Windows. Можно установить только пакеты приложений appx, которые разрабатываются для использования HoloLens. это можно увидеть в Microsoft Store с небольшой эмблемой рядом с приложением, которое показывает устройство HoloLens. Любой элемент управления, который вы используете для управления приложениями Магазина, также применяется к HoloLens. Вы можете использовать концепцию официального магазина или магазина для бизнеса. приложения могут быть загружены на один момент времени (вручную, чтобы загрузить приложение на устройство Windows) или можно управлять через MDM, чтобы приложения автоматически извлекаются из магазина при необходимости.
  - question: >
      Какова частота обновлений приложений в магазине для HoloLens?
    answer: >
      * по мере того, как мы соблюдаем ту же концепцию Microsoft Store и извлечь приложения из нее, цикл обновления определяется разработчиком приложения. все параметры управления, которыми необходимо управлять механизмом обновления в магазине, применяются также HoloLens.
  - question: >
      Есть ли возможность безопасной загрузки для HoloLens?
    answer: >
      * Да
  - question: >
      Есть ли возможность отключить или отключить поддержку периферийных устройств с устройства?
    answer: >
      * Да
  - question: >
      Есть ли возможность контролировать или отключать использование портов на устройстве?
    answer: >
      * HoloLens содержит только два порта (один для наушников и один для оплаты или подключения к пк). Невозможно отключить порт из-за функциональности и причин восстановления.
  - question: >
      Антивирус, обнаружение конечных точек, IP-адреса, список разрешенных элементов управления приложениями — любая возможность запускать антивирусные программы, обнаруживать конечные точки, IP-адреса, списки разрешенных элементов управления приложениями и т
    answer: >
      * Windows Holographic for Business (коммерческий набор) поддерживает Защитник Windows Smart Screen. если антивирусной компании нужно создать и опубликовать свое приложение на универсальная платформа Windows, его можно загрузить на HoloLens. В настоящее время ни одна компания не выполнила это для HoloLens.

      * возможность предоставления приложений с помощью Microsoft Enterprise Store, где можно выбрать только конкретные приложения, которые можно скачать. Кроме того, с помощью MDM можно заблокировать, какие приложения можно запускать или даже просматривать на устройстве.
  - question: >
      Можно ли помещать устройство в карантин, пока не обновите устройство, если оно было автономным в течение продолжительного периода времени?  Например: Устройство находится в ящике, который не включен в течение периода (шесть месяцев) и не получил никаких обновлений, исправлений и т. д.  Когда она попытается подключиться к сети, можно пометить ее и сказать, что необходимо обновить в другой сети перед тем, как присоединиться к сети.
    answer: >
      * Это то, что можно управлять на уровне инфраструктуры либо с помощью MDM, либо с локального сервера. Устройство можно пометить как несоответствующее, если оно не соответствует заданной версии обновления.
  - question: >
      Включает ли корпорация Майкрософт любые обратные двери или доступ к службам, которые позволяют корпорации Майкрософт подключаться к устройству для совместного использования экрана или удаленной поддержки?
    answer: >
      * Нет
  - question: >
      При создании сертификата PKI для доверенного взаимодействия мы хотим, чтобы сертификат был создан на устройстве, чтобы мы знали, что он только на этом устройстве, уникален для этого устройства и не может быть экспортирован или использован для олицетворения устройства. Это верно для HoloLens? Если нет, есть ли вероятность снижения риска?
    answer: >-
      * CSR для SCEP создается на самом устройстве. Intune и локальный Соединитель SCEP помогают защищать запросы, добавляя и проверяя строку запроса, которая отправляется клиенту.

      * поскольку HoloLens (1-й и второй) имеет модуль tpm, эти сертификаты будут храниться в модуле tpm и не могут быть извлечены. Кроме того, даже если их можно извлечь, не удалось проверить строки запроса на другом устройстве, выполняя визуализацию сертификатов или ключа на разных устройствах.
